### ISSUE TITLE
Commercial customer sign-up form validation/display tightening

### ISSUE THREAD

**Issue by mayhem** [metabrainz/metabrainz.org#103]
* [x] For all users signing up, please require a country.
* [x] For all users signing up, please require the short and long descriptions. (see below)
* [x] Short descriptions should be limited to 150 characters max. 
* [x] For users signing up with invoicing options, please require all address fields. (street, city, state, postal code)

In the same form we should change the text for the short description to be:

"How are you using our data? (max 150 characters; this will be shown on the site)."

Long description text:

"Please tell us about your company and your plans for using our data". (this will not be shown on the site)

The following fields should be marked with "This field is shown publicly": Org name, web url, logo url, api, url, short desc.

**Comment by gentlecat** [comment]
Long description is actually displayed publicly on page with tier details: https://github.com/metabrainz/metabrainz.org/blob/master/metabrainz/templates/users/tier.html#L33.

**Comment by mayhem** [comment]
Let's not show the long description at all then.

**Comment by gentlecat** [comment]
1-3 are implemented in PR #110.

**Comment by gentlecat** [comment]
Also need to add a note about which fields are going to be public.
