### ISSUE TITLE
Live Data Feed support

### ISSUE THREAD

**Issue by tsukanov** [metabrainz/metabrainz.org#54]
**TODO:**

* [x] User accounts (integration with MusicBrainz, sessions) - #55
* [x] Token management interface for users (revoke existing, etc.) - #56
* [x] Token management interface for admins - #70
* [x] Data access and tracking
